import { motion } from "motion/react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "./ui/dialog";
import { Button } from "./ui/button";
import { Copy, Download } from "lucide-react";

interface FHIRModalProps {
  isOpen: boolean;
  onClose: () => void;
  disease: {
    name: string;
    icdCode: string;
    namasteCode: string;
    ayushCode: string;
  };
}

export function FHIRModal({ isOpen, onClose, disease }: FHIRModalProps) {
  if (!disease) return null;

  // Convert details into plain text format
  const formatAsText = (d: typeof disease) => `
FHIR Condition Details

Disease Information
-------------------
Name: ${d.name}
ICD-11 Code: ${d.icdCode}
NAMASTE Code: ${d.namasteCode}
AYUSH Code: ${d.ayushCode}

FHIR Metadata
-------------
Resource Type: Condition
Clinical Status: Active
Verification Status: Confirmed
Recorded Date: ${new Date().toISOString().split("T")[0]}
Subject: Patient Reference

Integrations
------------
- NAMASTE Compliant
- AYUSH Integrated
- ABDM Ready
  `.trim();

  const diseaseText = formatAsText(disease);

  // Copy to clipboard
  const handleCopy = () => {
    navigator.clipboard.writeText(diseaseText);
    alert("Copied to clipboard!");
  };

  // Download as .txt file
  const handleDownload = () => {
    const blob = new Blob([diseaseText], { type: "text/plain" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${disease.name || "disease-details"}.txt`;
    link.click();
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-hidden flex flex-col">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle>FHIR Condition Details</DialogTitle>
          <DialogDescription>
            Readable details of the FHIR resource for <b>{disease.name}</b>
          </DialogDescription>
        </DialogHeader>

        {/* Animated Content */}
        <motion.div
          className="flex-1 overflow-auto"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
        >
          {/* Text content in a block */}
          <pre className="bg-white dark:bg-gray-900 rounded-lg p-4 border shadow-sm text-sm whitespace-pre-wrap">
            {diseaseText}
          </pre>
        </motion.div>

        {/* Footer with Copy/Download */}
        <div className="flex-shrink-0 pt-4 border-t flex items-center justify-between">
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleCopy}>
              <Copy className="w-4 h-4 mr-1" /> Copy
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownload}>
              <Download className="w-4 h-4 mr-1" /> Download
            </Button>
          </div>
          <div className="text-xs text-muted-foreground">
            FHIR R4 Compliant • Generated by CareSync v1.0
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}